### ISSUE TITLE
Does not compile on Darwin

### ISSUE THREAD

**Issue by jml** [silentbicycle/autoclave#12]
I went to try out autoclave, but found out that it does not compile on Darwin:

```
$ make
cc -c -o build/main.o -std=c99 -D_POSIX_C_SOURCE=200112L -g -Wall -pedantic -Wextra  -O3 src/main.c
src/main.c:101:31: error: use of undeclared identifier 'SIGRTMAX'
        if (res <= 0 || res > SIGRTMAX) { return -1; }
                              ^
1 error generated.
make: *** [build/main.o] Error 1
```

`SIGRTMAX` appears to be a Linux thing that has been ported back to FreeBSD but has not yet made its way to Darwin. I'm running OS X 10.13.6:

```
$ uname -a
Darwin hope.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,2 Darwin
$ cc -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks!

**Comment by silentbicycle** [comment]
Thanks for the detailed bug report. I'm going to investigate whether there are other POSIX-mandated constants for the upper limit for valid signal numeric IDs, but in the mean time if you change that locally to `res > 32` you should be able to build and try it out.

In the worst case, I could just let the user specify an invalid signal ID there and have `kill` return `EINVAL` when it tries to use the invalid signal, but I'd prefer to catch and warn about it upfront.

**Comment by silentbicycle** [comment]
Confirmed that this still builds on Darwin 16.7.0, so the breakage is fairly recent. It looks like POSIX doesn't have a standard symbol for the number of signals (standardizing `NSIG` was discussed but apparently rejected), and Darwin doesn't support RT signals.

I'll push a branch with a candidate fix for that shortly, please let me know if that builds for you.
**Edit:** Please try the `develop-remove-SIGRTMAX` branch.

**Comment by jml** [comment]
Thanks! That branch builds successfully for me.

**Comment by silentbicycle** [comment]
Great! Merged to `develop` -- this will be in the next versioned release.
